# Generated by Django 6.1.1 on 2026-10-01 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_signing_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUpdateSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
