name: Node Tests

inputs:
  command:
    description: Command to execute in the Node environment
    required: true
  websocket:
    description: Start collaboration WebSocket server before running
    default: 'false'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Bootstrap environment
      shell: bash
      run: |
        if [ "${{ inputs.websocket }}" = "true" ]; then
          scripts/env-setup.sh --collab
        else
          scripts/env-setup.sh
        fi

    - name: Run command
      shell: bash
      env:
        FORCE_COLOR: "1"
      run: ${{ inputs.command }}
