name: Node Tests

inputs:
  command:
    description: Command to execute in the Node environment
    required: true
  websocket:
    description: Start collaboration WebSocket server before running
    default: 'false'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Install dependencies
      shell: bash
      run: npm ci --no-audit --no-fund

    - name: Start WebSocket server
      if: ${{ inputs.websocket == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        npm run websocket &
        echo $! > ws-server.pid
        for _ in {1..20}; do
          if nc -z localhost 8080; then
            exit 0
          fi
          sleep 1
        done
        echo "WebSocket server failed to start" >&2
        exit 1

    - name: Run command
      shell: bash
      env:
        FORCE_COLOR: "1"
      run: ${{ inputs.command }}

    - name: Stop WebSocket server
      if: ${{ always() && inputs.websocket == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        if [ -f ws-server.pid ]; then
          kill $(cat ws-server.pid) || true
          rm -f ws-server.pid
        fi
