name: Node Tests

inputs:
  command:
    description: Command to execute in the Node environment
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v5
      with:
        node-version: 22

    - name: Bootstrap environment
      shell: bash
      run: scripts/env-setup.sh

    - name: Run command
      shell: bash
      env:
        FORCE_COLOR: "1"
      run: ${{ inputs.command }}
