catalogMode: prefer

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - undici-types@6.21.0
  - semver@6.3.1
overrides:
  body-parser: 2.2.1
  express: '>=5.2.0'
  js-yaml: 4.1.1
  qs: 6.14.1

catalog:
  '@antfu/eslint-config': ^7.2.0
  '@eslint-react/eslint-plugin': ^2.8.1
  '@lexical/clipboard': ^0.39.0
  '@lexical/devtools-core': ^0.39.0
  '@lexical/eslint-plugin': ^0.39.0
  '@lexical/history': ^0.39.0
  '@lexical/list': ^0.39.0
  '@lexical/markdown': ^0.39.0
  '@lexical/react': ^0.39.0
  '@lexical/rich-text': ^0.39.0
  '@lexical/utils': ^0.39.0
  '@lexical/yjs': ^0.39.0
  '@mantine/core': ^8.3.13
  '@mantine/hooks': ^8.3.13
  '@playwright/test': ^1.58.0
  '@tabler/icons-react': ^3.36.1
  '@tanstack/react-router': ^1.157.17
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@testing-library/user-event': ^14.6.1
  '@types/estree': ^1.0.8
  '@types/jsdom': ^27.0.0
  '@types/node': ^25.1.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  '@types/ws': ^8.18.1
  '@vitejs/plugin-react-swc': ^4.2.2
  '@vitest/coverage-v8': ^4.0.18
  '@vitest/ui': ^4.0.18
  '@y-sweet/client': ^0.9.1
  '@y-sweet/react': ^0.9.1
  '@y-sweet/sdk': ^0.9.1
  chokidar-cli: ^3.0.0
  concurrently: ^9.2.1
  cross-env: ^10.1.0
  dotenv-flow: 4.1.0
  eslint: ^9.39.2
  eslint-plugin-compat: ^6.1.0
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.26
  eslint-plugin-unicorn: ^62.0.0
  jiti: ^2.6.1
  jsdom: ^27.4.0
  lexical: ^0.39.0
  lib0: ^0.2.117
  markdownlint-cli2: ^0.20.0
  nanoid: ^5.1.6
  react: ^19.2.4
  react-dom: ^19.2.4
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vitest: ^4.0.18
  vitest-preview: ^0.0.3
  ws: 8.19.0
  y-protocols: ^1.0.7
  y-sweet: ^0.9.1
  yjs: ^13.6.29
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - leveldown
  - y-sweet
