version: "1"
services:
- type: web
  name: remdo
  runtime: docker
  repo: https://github.com/remdo-project/remdo
  branch: main
  plan: starter
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./docker/Dockerfile
  autoDeployTrigger: commit
  envVars:
    - key: PORT
      value: "8080"
    - key: PORT_BASE
      value: "8080"
    - key: AUTH_SECRET
      sync: false
    - key: ADMIN_SECRET
      sync: false
    - key: YSWEET_AUTH_KEY
      sync: false
    - key: YSWEET_SERVER_TOKEN
      sync: false
    - key: APP_PUBLIC_URL
      sync: false
    - key: ALLOW_SIGNUP
      value: "false"
  disk:
    name: remdo-data
    mountPath: /data
    sizeGB: 1
