name: Setup pnpm workspace
description: Set up Node.js and install dependencies using pnpm
inputs:
  node-version:
    description: Node.js version to use
    default: '22'
    required: false
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
