#!/usr/bin/env sh
set -eu
# shellcheck disable=SC3040
set -o pipefail 2>/dev/null || true

SNAPSHOT_BIN=${SNAPSHOT_BIN:-/usr/local/bin/snapshot.mjs}
TARGET_ROOT=${TARGET_ROOT:-/data}
TARGET_DIR="${TARGET_ROOT%/}/backup"
PORT=${APP_PORT:-${PORT:-8080}}
HOST=${HOST:-127.0.0.1}
COLLAB_SERVER_PORT=${COLLAB_SERVER_PORT:-${YSWEET_PORT_INTERNAL:-8081}}
COLLAB_CLIENT_PORT=${COLLAB_CLIENT_PORT:-$PORT}
NODE_ENV=${NODE_ENV:-production}

if [ ! -x "$SNAPSHOT_BIN" ]; then
  echo "snapshot binary not found at $SNAPSHOT_BIN" >&2
  exit 1
fi

mkdir -p "$TARGET_DIR"
HOST="$HOST" PORT="$PORT" COLLAB_SERVER_PORT="$COLLAB_SERVER_PORT" COLLAB_CLIENT_PORT="$COLLAB_CLIENT_PORT" NODE_ENV="$NODE_ENV" \
  "$SNAPSHOT_BIN" save "$TARGET_DIR/main" --md
HOST="$HOST" PORT="$PORT" COLLAB_SERVER_PORT="$COLLAB_SERVER_PORT" COLLAB_CLIENT_PORT="$COLLAB_CLIENT_PORT" NODE_ENV="$NODE_ENV" \
  "$SNAPSHOT_BIN" save "$TARGET_DIR/project" --doc project --md
