# Generated by Django 6.1.1 on 2026-09-15 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=documents.models.document_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                (
                    "kind",
                    models.CharField(
                        choices=[("document", "Document"), ("home", "Home")],
                        default="document",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "home")),
                        fields=("owner",),
                        name="one_home_per_user",
                    )
                ],
            },
        ),
    ]
