name: Setup pnpm workspace
description: Configure pnpm and install dependencies
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        node-version: 24.12.x
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
