name: Setup workspace
description: Configure Node and Python and install locked dependencies
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v6
    - uses: actions/setup-node@v7
      with:
        node-version: 24.21.x
        cache: pnpm
    - run: pnpm install --frozen-lockfile --prefer-offline
      shell: bash
    - uses: ./.github/actions/setup-python
