name: Vitest

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install Dependencies
        run: |
          npm ci --no-audit --no-fund
      - name: Run Vitest
        run: |
          npm run test-unit
