name: Serialization

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/node-test-shared
        with:
          command: |
            VITEST_SERIALIZATION_FILE=tree_complex npm run test-serialization
