name: Playwright Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Run shared Playwright action
        id: shared
        uses: ./.github/actions/test-browser-shared
        with:
          command: npm run test-browser
