name: Tests/Unit/Collab

on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/node-test-shared
        with:
          command: FORCE_WEBSOCKET=true npm run test-unit-collab
          websocket: true
