name: Playwright Tests

on: push

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run Playwright suite
        uses: ./.github/actions/test-browser-shared
        with:
          command: npm run test-browser
