name: Tests/Browser

on: push

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run Playwright suite
        uses: ./.github/actions/test-browser-shared
        with:
          command: npm run test-browser

      - name: Upload Playwright report
        if: ${{ hashFiles('data/playwright-report/index.html') != '' }}
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages
          path: data/playwright-report
