name: Serialization

on: push

permissions:
  contents: read

jobs:
  test:
    # FIXME(remdo): Disabled until serialization fixtures match minimized output (see GH-XXXX).
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/node-test-shared
        with:
          command: |
            # FIXME(remdo): Set VITEST_SERIALIZATION_FILE directly in package.json so local runs
            # and CI share the same entry point.
            VITEST_SERIALIZATION_FILE=tree_complex npm run test-serialization
