name: Serialization Smoke Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VITEST_SERIALIZATION_FILE: tree_complex
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Install Dependencies
        run: |
          npm ci --no-audit --no-fund
      - name: Run serialization test
        run: |
          npm run test-serialization
