name: Playwright Collab Tests

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  call-shared:
    uses: ./.github/workflows/test-browser-shared.yml
    with:
      collab: true
