name: Unit Tests
permissions:
  contents: read

on: push

jobs:
  unit-tests:
    permissions:
      contents: read
      actions: write
    name: Unit Tests
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-pnpm
      - env:
          TEST_TIMEOUT: 240
        run: pnpm run test:unit:full
