name: Unit Tests
permissions:
  contents: read

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    permissions:
      contents: read
      actions: write
    name: Unit Tests
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-pnpm
      - env:
          TEST_TIMEOUT: 360
        run: pnpm run test:unit

  backend-tests:
    timeout-minutes: 8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-python
      - run: ./tools/check-backend.sh && ./tools/django.sh test accounts documents fixtures remdo
